DOC: info update to conform with latest aiida-core
aiidateam/aiida-hyperqueue pull request #16
Opened 2024-04-30 14:09 UTC by unkcpz

minor changes in documentation. 
- `ssh` -> `core.ssh`
- In eiger it has the new scratch folder path.
- Update the hq latest version for download.

2024-05-01 15:32 UTC, mbercx requested changes
Thanks @unkcpz! I've left some comments.

2024-05-01 15:32 UTC, mbercx commented on pyproject.toml
> +version = "0.1.1"
Ah, shucks, we should also grab this dynamically now, see:

https://github.com/aiidateam/aiida-quantumespresso/blob/7b6c210a80942aed8ed08fa78f0d123d3227e750/pyproject.toml#L7

2024-05-01 15:32 UTC, mbercx commented on docs/source/get_started.md
> +For the older version of HyperQueue, you can change the version number in the URL.
Actually, since some changes might rely on a more recent hyperqueue version, I'd stick with the version I've tested (v0.16.0). Unless you've tested it for other versions, but I'm quite sure for some versions it will break.

2024-07-17 12:34 UTC, unkcpz commented on pyproject.toml
> +version = "0.1.1"
```suggestion
dynamic = ['version']
```

2024-07-17 12:37 UTC, unkcpz commented on docs/source/get_started.md
> +For the older version of HyperQueue, you can change the version number in the URL.
I test it from `0.16` ~ `0.19`. The `0.18.0` should be a suggested one, since they drop `hq dashboard` for the moment (https://github.com/It4innovations/hyperqueue/issues/725)

2024-07-18 08:18 UTC, merged